Repository pySmartThings/pysmartthings, pull requests merged in 2025-03, with the labels that each got.

#180 Add samsungce.dryerLabelScanCyclePreset
  src/pysmartthings/capability.py
Labels: new-feature

#183 Add `samsungce.ovenDrainageRequirement`
  src/pysmartthings/capability.py
Labels: bugfix

#184 Fix no mac address
  src/pysmartthings/models.py
  tests/__snapshots__/test_device.ambr
  tests/fixtures/devices_17.json
  tests/test_device.py
Labels: bugfix

#186 Add commands samsungce.washerOperatingState and samsungce.washerBubbleSoak
  src/pysmartthings/command.py
Labels: bugfix

#187 Add commands for future select entities
  src/pysmartthings/command.py
Labels: bugfix

#191 Add more capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#190 Enable raw data retrieval
  src/pysmartthings/smartthings.py
Labels: new-feature

#192 Fix OCF not being complete
  src/pysmartthings/models.py
  tests/__snapshots__/test_device.ambr
  tests/fixtures/devices_16.json
Labels: bugfix

#195 Add more capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#197 Add more capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#199 Add more capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#201 Add unspecified device listeners
  src/pysmartthings/smartthings.py
Labels: new-feature

#200 Add therac fixture
  tests/__snapshots__/test_device.ambr
  tests/fixtures/device_status/da_ac_therac_01011.json
  tests/fixtures/devices_18.json
  tests/test_device.py
Labels: maintenance

#204 Automate attribute generation
  .github/workflows/generate.yaml
  script/generate_enums.py
Labels: maintenance

#207 Add more capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#213 Add room move lifecycle
  src/pysmartthings/models.py
  tests/fixtures/room_move_event.json
Labels: bugfix

#214 Add Others Category
  src/pysmartthings/models.py
Labels: bugfix

#215 Add more capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#217 Fix headers
  src/pysmartthings/smartthings.py
  tests/const.py
Labels: bugfix

#223 Add capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#228 Add capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#229 Refactor SSE
  poetry.lock
  pyproject.toml
  src/pysmartthings/__init__.py
  src/pysmartthings/exceptions.py
  src/pysmartthings/models.py
  src/pysmartthings/smartthings.py
  tests/test_device.py
  tests/test_location.py
  tests/test_room.py
  tests/test_scenes.py
Labels: bugfix

#232 Add capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#242 Add capabilities
  src/pysmartthings/capability.py
  src/pysmartthings/models.py
Labels: bugfix

#243 Cap11
  src/pysmartthings/capability.py
Labels: bugfix

#248 Add capabilities
  src/pysmartthings/capability.py
Labels: bugfix

#252 Make sure we only log a missing capability once
  src/pysmartthings/models.py
  tests/test_device.py
Labels: bugfix

#253 Generate capabilities as well
  script/generate_enums.py
  src/pysmartthings/attribute.py
  src/pysmartthings/capability.py
  src/pysmartthings/command.py
Labels: maintenance

#255 Add pagination to device url
  src/pysmartthings/models.py
  src/pysmartthings/smartthings.py
  tests/__snapshots__/test_device.ambr
  tests/fixtures/devices_continued.json
  tests/test_device.py
Labels: bugfix

#258 Catch 409's not always as sink error
  src/pysmartthings/smartthings.py
Labels: bugfix

#270 Catch client connection errors
  src/pysmartthings/smartthings.py
Labels: bugfix

#278 Store device components as dict
  src/pysmartthings/models.py
  tests/__snapshots__/test_device.ambr
Labels: breaking-change

#279 Add more types
  src/pysmartthings/__init__.py
  src/pysmartthings/models.py
Labels: new-feature

#271 Retry deletion
  src/pysmartthings/smartthings.py
Labels: bugfix

#283 Catch client error
  src/pysmartthings/smartthings.py
Labels: bugfix
